name: Build Stable Docker Image

# Stable Docker images are built for every new tag
on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - README.md

env:
  IMAGE: ghcr.io/lukeberry99/polly-and-luke

  TAGS: |
    type=semver,pattern={{version}}

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Push to both Docker Hub and Github Container Registry
          images: ${{ env.IMAGE }}
          # Automatically update :latest
          flavor: latest=true
          tags: ${{ env.TAGS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push alpine image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
